name: Secrets and Environment Variables
on:
  workflow_dispatch
jobs:
  staging-environment:
    runs-on: ubuntu-24.04
    environment: staging
    env:
      #Inject Repository level secrets and variables
      Example_Repository_secret: ${{secrets.Example_Repository_secret}}
      Example_Repository_variable: ${{vars.Example_Repository_variable}}
      #Inject Environment level secrets and variables
      Example_Environment_secret: ${{secrets.Example_Environement_secret}}
      Example_Environment_variable: ${{vars.Example_Environment_variable}}
    steps:
      - name: access-staging-secrets-values
        run: |
          echo "Repo Secret (masked):    $Example_Repository_secret"
          echo "Repo Variable       :    $Example_Repository_variable"
          echo "Env Secret (masked) :    $Example_Environment_secret"
          echo "Env Variabele       :    $Example_Environment_variable"
  production-environment:
    runs-on: ubuntu-24.04
    environment: production
    env:
      #Inject Repository level secrets and variables
      Example_Prod_Repository_secret: ${{secrets.Example_Repository_secret}}
      Example_Prod_Repository_variable: ${{vars.Example_Repository_variable}}
      #Inject Environment level secrets and variables
      Example_Prod_Environment_secret: ${{secrets.Example_Environement_secret}}
      Example_Prod_Environment_variable: ${{vars.Example_Environment_variable}}
    steps:
      - name: access-production-secrets-values
        run: |
          echo "Prod Repo Secret (masked) :   $Example_Prod_Repository_secret"
          echo "Prod Repo Var             :   $Example_Prod_Repository_variable"
          echo "Prod Env Secret (masked)  :   $Example_Prod_Environment_secret"
          echo "Prod Env Variable (masked):   $Example_Prod_Environment_variable"
      